### ISSUE TITLE
The screen does not update when we import settings

### ISSUE THREAD

**Issue by robsonpiere** [boazpoolman/strapi-plugin-config-sync#110]
### Describe the bug

After importing the data, the screen still shows the same data to import.

### Steps to reproduce the behavior

1. Go to Config Sync interface menu
2. Click on Import content types configs
3. The data is updated on database, but not in screen.

### Expected behavior

The imported files should disappear from the list without needing to restart the application.

### Screenshots

![error-plugin](https://github.com/boazpoolman/strapi-plugin-config-sync/assets/11904136/877f33aa-669b-49ff-912c-d4d98853e2fe)

### Code snippets

N/A

### System

- Node.js version: 18.18
- NPM version: yarn 1.22.19
- Strapi version: 4.14.5
- Plugin version: 1.2.1
- Database: Postgres 15
- Operating system: Debian 12 / Alpine

### Additional context

In console you can see ` Use Query Engine API instead of Entity Service API for type core-store`

**Comment by boazpoolman** [comment]
Can you confirm this issue isn’t introduced since version 1.2. You can do that by explicitly installing version 1.1.3 and seeing if the problem still occurs

**Comment by robsonpiere** [comment]
> Can you confirm this issue isn’t introduced since version 1.2. You can do that by explicitly installing version 1.1.3 and seeing if the problem still occurs

@boazpoolman I tested today on versions 1.1.3 and 1.2.0

In version 1.2.0 the error occurs.
In version 1.1.3 the error does not occur.

**Comment by boazpoolman** [comment]
I'm seeing another issue (#109), also happening since `1.2.0` and I think they might be caused by the same problem.
I've attempted to fix that by doing some changes in this PR #111.

Could you test that out to see if it solves this issue aswell?

You can install the PR like so:

```
yarn add boazpoolman/strapi-plugin-config-sync#pull/111/head
```

**Comment by robsonpiere** [comment]
@boazpoolman In this version

I no longer see the Use Query Engine API instead of Entity Service API for type core-store message in the console.

After importing the configuration, I see that the configuration was imported, but the file still appears in the list with changes to the id, createdAt and UpdatedAt fields, removing them from the configuration.

Restarting the application the difference disappears


Diff before import

![image](https://github.com/boazpoolman/strapi-plugin-config-sync/assets/11904136/cbb0fb09-0ccb-4572-8732-4db3d5a5c83e)

Diff after import

![image](https://github.com/boazpoolman/strapi-plugin-config-sync/assets/11904136/9efb7576-1d2c-47d2-be12-27831e08478d)

Diff after restart:

![image](https://github.com/boazpoolman/strapi-plugin-config-sync/assets/11904136/c493e04e-d3ed-4a4c-9b34-ccb61b57a1ef)

**Comment by boazpoolman** [comment]
Thanks for testing the PR @robsonpiere

I was able to replicate the issue by manually updating a config file and then importing.
This issue only happend for me with `core-store.plugin_content_manager_configuration_content_types.....` config files.
I've also confirmed that this issue has been introduced in version 1.2.0 as downgrading to 1.1.3 fixes the issue for me.

Sadly the PR doesn't provide a solution for this problem.
Currently investigation solutions.

**Comment by boazpoolman** [comment]
I've attempted to fix this issue in PR #113.

Could you test that fix on your end?
You can install the PR like so:

```
yarn add boazpoolman/strapi-plugin-config-sync#pull/113/head
```

**Comment by robsonpiere** [comment]
I tested it and now it's ok! 🎉 

I just see a message in the console, but I get no error.

` [strapi-plugin-config-sync]: Use Query Engine API instead of Entity Service API for type core-store `

**Comment by MSACC** [comment]
Fixed in https://github.com/boazpoolman/strapi-plugin-config-sync/pull/113

**Comment by AliKdhim87** [comment]
I believe the issue remains unresolved since a new patch hasn't been released yet.

**Comment by boazpoolman** [comment]
You're correct. I've re-opened.
Can be closed as soon as it's been released.

**Comment by boazpoolman** [comment]
The fix has been released with [v1.2.2](https://github.com/boazpoolman/strapi-plugin-config-sync/releases/tag/1.2.2)

If you're still having this, or any other issue with the plugin beyond v1.2.2 please feel free to open a new issue.
