### ISSUE TITLE
Plugin is failing when clean and build after strapi upgrade

### ISSUE THREAD

**Issue by saifmattias** [boazpoolman/strapi-plugin-config-sync#35]
## Bug report
Getting ModuleNotFoundError when building the plugin with strapi 4.0.3

### Describe the bug
ModuleNotFoundError: Module not found: Error: Can't resolve 'immutable' in '<Project name>/node_modules/strapi-plugin-config-sync/admin/src/helpers'

I am getting this when trying to build after the upgrade for strapi 4.0.3

### Steps to reproduce the behavior

1. Upgrade strapi to 4.0.3
2. Run npm run build --clean
3. The error shows up

### Expected behavior
Run run build without error

### System

- Node.js version: Tested with version 14 (npm v8.3.0) and 16 (npm v8.1.0)
- Strapi version: 4.0.3
- Plugin version: 1.0.0-beta.1
- Database: Postgressql
- Operating system: locally

**Comment by boazpoolman** [comment]
That’s weird. I’ll check it out.
Thanks for submitting the issue.

**Comment by du0ngtrunghieu** [comment]
I also have the same problem, hope you fix it as soon as possible 

**System**
    Strapi version: 4.0.3
    Plugin version: 1.0.0-beta.1
    Database: Postgressql
    Operating system: heroku

**Comment by boazpoolman** [comment]
So it seems Strapi has removed `immutable` and `redux-immutable` as dependencies since `4.0.3`.
This plugin relied on those, so I've added them as direct dependencies of the plugin.

Thanks again for the quick issue submissions!

Should be fixed in `v1.0.0-beta.2`

**Comment by mlouage** [comment]
Hi @boazpoolman . Still getting that error with beta.2. I also use Postgres as the database.

```bash
❯ yarn cs export
yarn run v1.22.17
$ config-sync export
/home/<username>/Play/strapi-postgresql/cms/node_modules/strapi-plugin-config-sync/server/cli.js:163
program.storeOptionsAsProperties(false).allowUnknownOption(true);
        ^

TypeError: program.storeOptionsAsProperties is not a function
```

**Comment by boazpoolman** [comment]
Oh wtf, this is a different issue.
Just tested it though, didn't have any issues.

Thanks. I'll take a look.

**Comment by mlouage** [comment]
Oops, you're right. Sorry, must have been in a hurry to miss that. Thanks!

**Comment by boazpoolman** [comment]
@mlouage just tested it, works fine on my end.
Can you maby create a new issue following the issue template?
Providing system versions etc :)

**Comment by boazpoolman** [comment]
@du0ngtrunghieu or @saifmattias
Can one of you confirm that `v1.0.0-beta.2` fixes the initial issue?

**Comment by boazpoolman** [comment]
It's been a week, and I'm pretty sure this has been fixed.

I'm closing the issue now.
